# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

# [[main]]
#   name = "Recent Activities"
#   url = "#recents"
#   weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Papers We Read"
  url = "https://vlgiitr.github.io/papers_we_read/"
  weight = 41

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "Blogs"
  url = "blogs/"
  weight = 60

[[main]]
  name = "Recruitments"
  url = "recruitments/"
  weight = 62

[[main]]
  name = "Discussions"
  url = "discussions/"
  weight = 70

[[main]]
  name = "Team"
  url = "team/"
  weight = 80

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90

[[main]]
  name = "Archives"
  url = "archives/"
  weight = 91

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

